CREATE TABLE [dbo].[HostJob]
(
	[HostJobId] BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[JobId] BIGINT NOT NULL,
	[HostId] BIGINT NOT NULL, 
	[State] SMALLINT NOT NULL,
	[CreatedAt] DATETIME NOT NULL DEFAULT GETDATE(),
	[UpdatedAt] DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT [FK_HostJob_Job] FOREIGN KEY ([JobId]) REFERENCES [Job]([JobId]),
    CONSTRAINT [FK_HostJob_Host] FOREIGN KEY ([HostId]) REFERENCES [Host]([HostId])
)